### PR TITLE
Add a standard for structuring React Components for the Project

### LINKED ISSUE #103: Draft a standard structuring convention for the React Components
### Concerns Over Current Dev Practice

Since the project relies on Next.js, the concern about structuring files & directories for the project are pretty much covered as well! But Next.js doesn't provide any guidance on how to structure the many components a web app can have in it's lifetime. Yes, it's possible to dump all components under the `src/components` directory & call it a day but it can lead to a degree of ambiguity.

### Suggestions for an Improved Dev Practice

As such I reviewed a couple of resources which suggested an improved standard structuring formulae for React projects. Following are the resources & their suggestions:

1. "[_React Architecture: How to Structure and Organize a React Application_](https://www.taniarascia.com/react-architecture-directory-structure)" by Tania Rascia which suggests a directory structure for React SPA projects. The author advocates keeping everything related to a specific functionality in one single place. For e.g; keep all tests, style sheets & `.tsx` files under a one directory aptly named after that functionality. So, we could group `Footer.tsx`, `Footer.test.ts`, `Footer.styles.css` under the `src/components/Footer` directory.
2. "[_How I set up a Next.js project structure_](https://flaviocopes.com/nextjs-project-structure/)" by Flavio Copes recommends a "page" components structuring. So, all components & it's related files used in the `profile` page should be placed under the `src/components/Profile` directory.

### Ending Words

So, it appears there's no clear consensus on how exactly should components be structured but the aforementioned resources can definitely referred to as a source of inspiration. Keeping in mind scalability concerns & the scope of the project, I think we should pick the best of both the suggestions & build our own standards. Hence, this issue thread will keep track of drafting a standard practice of naming, structuring and/or any development practices of all the components used in the project.

That said, concerns, feedback and/or recommendations are very welcome! So please make the most out of the comment section below & share what you think.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Jarmos-san**
## Description

This PR contains a brief detail on structuring React Components for the project. The `CONTRIBUTING.md` & the `README.md` files are updated with the necessary info.

Fixes #103 

## Changes Include

- [x] This change requires a documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by Jarmos-san** [comment]
@afkcodes @Manav-SM @Bhupesh-V the PR contains some changes to the documentation so it would be nice to receive a second pair of eyes on it in case I missed out on some grammatical errors or something. So if you guys find something please feel free to point it out.

**Review by yashsharan0805 — COMMENTED** [review]
overall Looks good to me. i am assuming for other stuff (Utils, website tabs, etc) would be covered in a seperate PR

**Comment by afkcodes** [comment]
As we are using Tailwind Styles.ts will not be necessary for most of the components we make. we can make it optional.
I was thinking to introduce NEXT UI as a component library looks cool and modern and sleek UI

refer: https://github.com/nextui-org/nextui 

other things looks good to me at first go. we can anyway comeback and update it when needed.

**Review by Manav-SM — APPROVED** [review]

**Review by afkcodes — APPROVED** [review]

**Comment by Jarmos-san** [comment]
> overall Looks good to me. i am assuming for other stuff (Utils, website tabs, etc) would be covered in a seperate PR

@yashsharan0805 yes, I'll keep the contributing guidelines updated as & when there's a need to document a workflow. It's not possible to outright predict what sort of contributions will we receive & people have differing styles of writing code as well. So, I'm keep an option for future adjustments in case there's a need for it.

**Comment by Jarmos-san** [comment]
@afkcodes as I mentioned it earlier on Discord as well, I like the looks of [NextUI](https://nextui.org/) (& I'm in favour of using any sort of React Component Library like [Chakra-UI](https://chakra-ui.com/) as well!). But let's not switch context right now because quite a lot of people are onboard on this project already. And they're aware of the fact that the project uses TailwindCSS for it's styling requirements.

Regardless, I'll open a discussion thread & we can discuss the possible workflow for migrating the tech stack to using a Component lib instead of a CSS framework.

**Pull request merged**
