### PR TITLE
Attempt to fix the deployment workflow

### LINKED ISSUE #149: [BUG]: Fix & make the current CI/CD pipeline more robust
### What happened?

Currently the CI/CD pipeline isn't only inefficient but it doesn't work as expected either. Following are the intended behaviour but for whatever reason it doesn't work:

- Deploy to Netlify using GitHub Actions (causes an authentication issue even the auth tokens exists)
- Make a comment on the PR with a preview URL

The expected behaviour is basically to deploy the static contents to Netlify after they've been generated on the GitHub Actions environment. Once the deployment is successful, comment on the PR with a preview URL.

### Relevant log output

See https://github.com/developersIndia/website/runs/5703328348?check_suite_focus=true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Jarmos-san**
# Pull Request Template

## Description

The PR contains an updated workflow file which "should fix" the current CI/CD pipeline.

Fixes #149 (if everything works as expected though)

## Changes Include

- [x] Bug fix 🐛 (non-breaking change which fixes an issue)
- [x] Refactor ⚒️ (code change that neither fixes a bug nor adds a feature)
- [x] Tooling ⚙️ (Changes to the build process or auxiliary tools and libraries such as documentation generation)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by Jarmos-san** [comment]
As I thought (and as I discussed over call) the the secret tokens are **correct** but the Action's environment couldn't access them for whatever reason (see the description of #149 for a possible explanation).

This PR makes it work somehow but further testing & experimentation is required to see if workflows triggered from forked pull requests can access the tokens or not. Regardless, this PR kinda fixed the concern we had with the CI/CD pipeline(?). At least now, it not only deploys to Netlify but also comments on the PR with a preview URL.

Do note, the preview URL shows a 404 page which I believe is because of a broken Next.js build (this should be fixed if #144 is merged to the `master` branch.

**Comment by Jarmos-san** [comment]
@Bhupesh-V can we merge after you review it so that we can test pull requests from forked repositories triggering the workflows have access to the secret tokens as well?

Having this PR merged to `master` will make it so much more easier to check what changes did people introduce to the website (the preview URL will help us on that regards, see comment above).

@Charan1973 @uragirii can you guys fork & send some trivial PRs to help us test the workflow works as we expect it to? But wait for us to merge it to `master` branch first.

**Comment by uragirii** [comment]
@Jarmos-san great work! The deployment url works correctly imo. But the problem may arise when forking and creating a PR (most common use-case for this repo) 

> @charan1973 @uragirii can you guys fork & send some trivial PRs to help us test the workflow works as we expect it to? But wait for us to merge it to master branch first.

Sure, will do. afaik i would get an email once this PR is merged and then I would create a trivial PR (yay! for the first contribution)

**Comment by Jarmos-san** [comment]
Leaving this [one comment](https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-852541544) I stumbled upon while trying to setup a work-related project as well.

**Pull request merged**
